### PR TITLE
[Feature] Match chart area to designs

### PR DESCRIPTION
**Pull request by nerdlet**
## Description

Fixes # 181432064

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Desktop Screenshots
Screenshot 2022-03-03 at 14 20 30

## Mobile Screenshots
Screenshot 2022-03-03 at 14 20 55

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Just confirm @nerdlet, why do we need the white background when we open the ratings dialogs?

**Comment by nerdlet** [comment]
> Just confirm @nerdlet, why do we need the white background when we open the ratings dialogs?

@kilemensi Um, for this I went ahead and followed the design here https://xd.adobe.com/view/4728124f-a7c3-472c-a8ef-574d5a602886-127b/ 
There is a background on it. Also, it could be that the reason we have that is to showcase the dialog paper alone.  So this is open to discussion. If we don't need it,  we don't need to implement it

**Comment by kilemensi** [comment]
> > Just confirm @nerdlet, why do we need the white background when we open the ratings dialogs?
> 
> @kilemensi Um, for this I went ahead and followed the design here https://xd.adobe.com/view/4728124f-a7c3-472c-a8ef-574d5a602886-127b/ There is a background on it. Also, it could be that the reason we have that is to showcase the dialog paper alone. So this is open to discussion. If we don't need it, we don't need to implement it

Personally I think this is an overlook on the designers' part @nerdlet . I don't think we've built any site where the modal background is 💯 opaque. But, lets ask the product champ: @KobbyMmo, over to you 🎙️

**Comment by KobbyMmo** [comment]
Yea, I think. we should not make the background opaque @nerdlet. I am sure the designers just built that in isolation.

**Pull request closed without merging**
