### PR TITLE
[FIX] Fix UI issues

### PR DESCRIPTION
**Pull request by nerdlet**
## Description

Fixes #181509978

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

##  Current
Screenshot 2022-03-09 at 15 42 04
Screenshot 2022-03-09 at 15 41 07
Screenshot 2022-03-09 at 15 40 54

##  Fix

Screenshot 2022-03-09 at 15 38 18

Screenshot 2022-03-09 at 15 37 22

Screenshot 2022-03-09 at 15 46 47

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by kilemensi** [comment]
Everything loads fine for me @nerdlet except Sonko on homepage

**Comment by nerdlet** [comment]
> Everything loads fine for me @nerdlet except Sonko on homepage

Ahhhh, okay..um, you need add  `IMAGE_DOMAINS` in your .env. I have already updated vercel with the new variable.

**Comment by kilemensi** [comment]
> > Everything loads fine for me @nerdlet except Sonko on homepage
> 
> @kilemensi Ahhhh, okay..um, you need to add `IMAGE_DOMAINS` in your .env. I have already updated vercel with the new variable.

It doesn't work on Vercel preview link @nerdlet : https://promisetracker-git-feature-minor-fixes-codeforafrica.vercel.app/

**Review by kilemensi — APPROVED** [review]
🚀

**Pull request merged**
